---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kojy5082/hotels/
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
